### ISSUE TITLE
Compatibility with FancyMenu animation loading screen.

### ISSUE THREAD

**Issue by Wedge1453** [Keksuccino/Drippy-Loading-Screen#1]
I made a custom loading screen, and I have an animation for the title screen using Fancy Menu, the animation loading shows the vanilla red screen with the Mojang logo instead of the custom loading screen I made.

**Comment by Keksuccino** [comment]
Hi! The animation loading screen is part of the old, deprecated animation system and will be removed soon (together with the old system). Please [convert your animation to the new format](http://fm.keksuccino.de/books/fancymenu-v22x/page/22x-animations) :)
