### ISSUE TITLE
[Forge 1.16.5] "Layout Auto-Scaling" is bugged entirely

### ISSUE THREAD

**Issue by mosharky** [Keksuccino/Drippy-Loading-Screen#11]
**Describe the bug**
Layout Auto-Scaling continuously down-scales the menu, to the point where it's no longer visible.

**To Reproduce**
1. Select "Layout Auto-Scaling"
2. Use 1080p values (1920x1080)
3. Watch, as the loading screen begins to scale down infinitely (regardless of resolution)

**Expected behavior**
The menu gets scaled down when the game is not at the set resolution values (in this case 1920x1080)

**Basic Informations (please complete the following information):**
 - OS: Window 10
 - Drippy Loading Screen Version: 1.4.1
 - Forge Version: 36.2.9
 - Minecraft Version: 1.16.5
 - Active Mods: [https://github.com/mosharky/Mos-Mods/blob/master/README.md](url)

the active mods are slightly outdated. Drippy Loading Screen and FancyMenu have been added since that list.

**Comment by Keksuccino** [comment]
Hi! Please try if it works without other mods installed. If this is the case, it's probably some sort of mod conflict.

Please also try to set a forced scale of 2 before enabling auto-scaling and see if this fixes it, thank you very much :)

**Comment by Keksuccino** [comment]
Closed because not reproducible and no response.
