### ISSUE TITLE
Optifine not working

### ISSUE THREAD

**Issue by ThijsjeboyGaming** [Keksuccino/Drippy-Loading-Screen#12]
**Describe the bug**

- Optifine (if enabled) will stop the custom loading screen from loading.
- It will still load the layout menu and settings bar (etc) but won't do anything while loading into Minecraft.
- https://i.imgur.com/nDL4aD7.png   -   Layout editor working without AND with Optifine

**To Reproduce**
0. Use 1.18, Forge 38.0.15
1. Go to the 'mods' folder
2. Add OptiFine_1.18_HD_U_H3_MOD 
3. Start Minecraft
4. See the error

**Expected behavior**
A clear and detailed description of what you expected to happen.

- The loading screen working. 

**Crash Log**
If the bug includes a crash, please paste or link it here.

- nope game doesn't crash

**Screenshots**
https://i.imgur.com/Xzw2Duq.png   ​- WITHOUT Optifine

https://i.imgur.com/qkcZS1B.png - WITH Óptifine

**Basic Informations (please complete the following information):**
​- OS: Windows 10 pro - 21H2
- Drippy Loading Screen Version - 1.4.1_MC_1.18
​- Forge/Fabric Version - forge 38.0.15
​- Minecraft Version 1.18
​- Active Mods OptiFine_1.18_HD_U_H3_MOD, loadmyresources_1.0.1_MC_1.18, konkrete_1.3.0_MC_1.18, fancymenu_2.4.2_MC_1.18, drippyloadingscreen_1.4.1_MC_1.18

**Comment by Keksuccino** [comment]
OOF.
Optifine changed a lot in 1.17+ and I don't know if I can fix this, as it looks like OF is overriding the loading screen??? But why should they do this..

Will look into it, thank you for telling me!

**Comment by Keksuccino** [comment]
Fixed in Drippy v1.4.2! Thank you for your report!
