### ISSUE TITLE
[Feature] Disable the DLS button per config

### ISSUE THREAD

**Issue by Taknax** [Keksuccino/Drippy-Loading-Screen#13]
A config to disable the DPS button. This could get implemented in the other customization mods like FancyHUD and Fancy Menu too. The effect would be, that only the modpackcreator could have the ability to cahnge the style. Sry for my english. I used the translator.

**Comment by Keksuccino** [comment]
Hi! This is already a thing :) You can disable the customization controls in the mod settings of both mods (click on the little DL or FM button in the top-left). The customization controls can also be toggled by pressing CTRL + ALT + [KEYBIND]. Look for the correct keybind in the MC controls settings.
