### ISSUE TITLE
Crash when loading minecraft

### ISSUE THREAD

**Issue by JetpackRescue** [Keksuccino/Drippy-Loading-Screen#14]
1.16.5
windows 10
drippy 1.5.0

when loading minecraft it crashes the game, here's the log
https://pastebin.com/uyy8aKDH

**Comment by Keksuccino** [comment]
Try it without OptiFine, please.

**Comment by JetpackRescue** [comment]
it's a random crash, it doesn't happen every single time, I need optifine for my modpack.

**Comment by Keksuccino** [comment]
Do you use a web texture in your layout?

**Comment by Keksuccino** [comment]
I've released an update (v1.5.1) that hopefully fixes this! Please try it with the new update and report back if the crash still happens or not, thank you!
