### ISSUE TITLE
Crash when launch with entering server

### ISSUE THREAD

**Issue by htser** [Keksuccino/Drippy-Loading-Screen#16]
1.18.2
Windows 11
Forge
here is the log: https://pastebin.com/mQsUEF7i  over 800KB

normal launch is ok, but i need auto-enter server, so added "-server xxxx -port nnnn" arguments, then crashed.

**Comment by Keksuccino** [comment]
Closed because full rewrite of mod. If this is still a problem, please open a new issue.
