### ISSUE TITLE
More Progress Bars

### ISSUE THREAD

**Issue by Brittank88** [Keksuccino/Drippy-Loading-Screen#20]
Akin to [Better Loading Screen](https://www.curseforge.com/minecraft/mc-mods/betterloadingscreen), progress bars for each loading stage as well as a memory usage bar would be fantastic. Currently there's no way (that I know of) to use this mod alongside a mod that adds those features, at least on Fabric.

**Comment by UnperishedDev** [comment]
Yes please more progress bars! (Loading stages, RAM usage, initialized mods, etc.)

**Comment by Keksuccino** [comment]
> Yes please more progress bars! (Loading stages, RAM usage, initialized mods, etc.)

There is a Generic Progress Bar element that can do RAM usage already. There are placeholders for that, so you can use these as progress value.

**Comment by UnperishedDev** [comment]
I tried adding that to my modpack, couldn't find anything on the [docs](https://fm.keksuccino.dev/en/wiki/general/verified/loading-screen). How would I add a progress bar for said placeholders? Does it have to be an integer value from 0-100, or can there be any placeholder?

**Comment by Keksuccino** [comment]
FancyMenu v3.0.0 and Drippy v3.0.0 are out now and they are full rewrites, so I'm closing this for now. If this is still a problem, please open a new issue, thank you.
