### ISSUE TITLE
Menu button deviates to the right

### ISSUE THREAD

**Issue by Moonlight522961** [Keksuccino/Drippy-Loading-Screen#21]
Describe the bug
My buttons shift to the right

To Reproduce

It happens when I reload the game

Screenshots

![捕获](https://user-images.githubusercontent.com/120054074/206277069-7ef278eb-a091-4032-ae29-67399ed0e270.PNG)

Basic Informations (please complete the following information):

OS: Window 10
Drippy Loading Screen Version: 1.6.6
Forge Version: 36.2.39
Minecraft Version: 1.16.5
Active Mods: I only installed this module and its front
（I use software to translate, and the sentences are not smooth. I'm sorry）

**Comment by Kasualix** [comment]
I also have this problem every time I enter the main menu.

**Comment by Keksuccino** [comment]
Closed because full rewrite of mod.
