### ISSUE TITLE
Drippy Loading Screen 2.0.0 Crashes on Start Up

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Keksuccino/Drippy-Loading-Screen#26]
**Describe the bug**
After upgrading to Drippy Loading Screen 2.0.0 for my pack, [Create on a Potato PC: Sky Edition](https://www.curseforge.com/minecraft/modpacks/create-on-a-potato-pc-sky) the client crashes on startup.

If I revert to v 1.6.6 the pack launches fine.

**Crash Report:** [formatted](https://crashy.net/TPNzBk2QJvQR2YEn2EwQ) [raw](https://crashy.net/TPNzBk2QJvQR2YEn2EwQ?raw)

**Environment:**
- Drippy Loading Screen 2.0.0
- Minecraft: 1.19.2
- Forge 43.2.3
- Java 17.0.5
- Linux Mint 20.3

**Mods**
- AI-Improvements 0.5.2
- AppleSkin 2.4.2+mc1.19
- Architectury 6.4.62
- AutoRegLib 1.8.2-55
- Bad Wither No Cookie Reloaded 3.14.1
- Balm 4.5.3
- Better Compatibility Checker 1.0.9-build.38+mc1.1
- Bisect Hosting Menu 1.19.2-1.3
- Bookshelf 16.2.17
- Client Tweaks 8.1.0
- Cloth Config v8 API 8.2.88
- Clumps 9.0.0+14
- Comforts 6.0.3+1.19.2
- Configured 2.0.1
- Controlling 10.0+7
- Crafting Station 1.19.2-6.0.1
- CraftingCraft 13.0.0
- CraftingTweaks 15.1.0
- Crash Utilities 6.2
- Create 0.5.0.i
- Create Crafts & Additions 1.19.2-20221230a
- Create Deco 1.2.12-1.19.2
- Create Jetpack 2.1.3
- Create Mechanical Extruder 1.19.2-1.3.2.h
- Create Sifter 1.19.2-1.3.3.g
- Create Stuff & Additions 2.0.2
- Curios API 1.19.2-5.1.1.0
- Default World Type 1.19.1-3.1.0
- DefaultSettings 2.8.7
- Drippy Loading Screen 2.0.0
- Easier Villager Trading 1.2.0
- Easy Emerald 1.4.15
- EnchantmentDescriptions 13.0.14
- Enhanced Mob Spawners 1.9.1
- FancyMenu 2.13.3
- Fast Workbench 7.0.1
- FastFurnace 7.0.0
- Ferrite Core 5.0.3
- Flywheel 0.6.8.a-14
- Forge 43.2.3
- FPS Reducer 1.19.2-2.1
- FTB Backups 2 1.0.17
- FTB Chunks 1902.3.15-build.233
- FTB Essentials 1902.1.10-build.47
- FTB Library 1902.3.11-build.166
- FTB Quests 1902.4.6-build.176
- FTB Ranks 1902.1.14-build.70
- FTB Teams 1902.2.12-build.95
- Game Menu Mod Option 1.18
- Gravestone Mod 1.19.2-1.0.1
- Item Filters 1902.2.9-build.46
- Just Enough Items 11.5.2.1007
- Konkrete 1.6.0
- Kotlin For Forge 3.9.1
- KubeJS 1902.6.0-build.140
- Library ferret 3.0.0
- LibX 1.19.2-4.2.8
- Light Overlay 7.0.1
- Lootr 0.3.20.57
- Minecraft 1.19.2
- Mouse Tweaks 2.23
- NetherPortalFix 10.0.0
- No Chat Reports 1.19.2-v1.5.1
- Oculus 1.2.8
- Patchouli 1.19.2-77
- Placebo 7.1.2
- PolyLib 1900.0.2-build.42
- Polymorph 0.46.1+1.19.2
- Powder Power 3.6.13
- Quark 3.4-389
- Repurposed Structures 6.3.8+1.19.2
- Rhino 1902.2.2-build.264
- Rubidium 0.6.2
- Rubidium Dynamic Lights 1.19.2_v1.4.0
- Rubidium Extras 1.19.2_v1.3.2
- Shifted Lib 1.0.2
- ShulkerBoxTooltip 3.2.2+1.19.2
- Shutup Experimental Settings! 1.0.5
- Sky GUIs 1.19.1-2.1.2
- Skyblock Builder 1.19.2-4.2.6
- SpectreLib 0.11.0+1.19
- Squat Grow 3.0.0-build.33+mc1.1
- Starlight 1.1.1+forge.a3aea74
- SwingThroughGrass 1.19.2-1.10.0
- Tempad 1.4.4
- The One Probe 1.19-6.2.2
- Tom's Simple Storage Mod 1.3.10
- Wither Skeleton Tweaks 8.0.0
- Witherproofed 2.7.4
- Xaero's Minimap 22.17.1
- Xaero's World Map 1.28.8

**Comment by FooterMan14** [comment]
I'm having this exact issue as well. This is correct.

**Comment by Keksuccino** [comment]
Fixed in Drippy v2.0.1! Thank you for reporting it!
