### ISSUE TITLE
Resource pack loading screen doesn't work like game launch screen

### ISSUE THREAD

**Issue by Wedge1453** [Keksuccino/Drippy-Loading-Screen#3]
so I joined a modded server that has a custom server resource pack, this is the loading screen I got, as you can see the loading bar is behind the logo, while in the modpack launch screen this problem doesn't occur, perhaps there is a difference between the 2 screens, or am I missing something?
![2021-09-03_17 34 24](https://user-images.githubusercontent.com/76813383/132256370-4f173402-671b-49f6-b53c-6ee12dfa43a1.png)

**Comment by Keksuccino** [comment]
Hi! Thank you for telling me. Will check this!

**Comment by Wedge1453** [comment]
I checked again and I realised that it's because I changed monitors, sorry for bothering you.

**Comment by Wedge1453** [comment]
and because the 2 elements didn't have the same orientation
