### ISSUE TITLE
Issue with 2.1.0

### ISSUE THREAD

**Issue by Sixdd6** [Keksuccino/Drippy-Loading-Screen#35]
**Describe the bug**
After setting up a new layout and restarting, the loading screen is just black with the custom loading bar I added flashing.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Make a custom loading screen including custom graphics and loading bar?

**Expected behavior**
Not an empty looking void with flashing loading bar.

**Game Log**
[latest.log](https://github.com/Keksuccino/Drippy-Loading-Screen/files/10593764/latest.log)
[debug.log](https://github.com/Keksuccino/Drippy-Loading-Screen/files/10593765/debug.log)

**Screenshots**
![Screenshot_20230203_081523](https://user-images.githubusercontent.com/29067133/216741229-f202b62b-afb6-4f1f-80c2-aa258365c41e.png)

**Basic Informations (please complete the following information):**
 - OS: Windows11
 - Drippy Version 2.1.0
 - Forge/Fabric Version Forge 40.2.0
 - Minecraft Version 1.18.2
 - Active Mods [modlist.txt](https://github.com/Keksuccino/Drippy-Loading-Screen/files/10593776/modlist.txt)

**Other Notes**
An interesting thing, if I let the game continue to the main menu the loading screen does eventually work as intended for a few seconds before the main menu appears.

Here is also an export of my setup to test with: [woohacraft5_exported_fm_setup_3-2-2023-20-31-13.zip](https://github.com/Keksuccino/Drippy-Loading-Screen/files/10593794/woohacraft5_exported_fm_setup_3-2-2023-20-31-13.zip)

**Comment by Keksuccino** [comment]
Please load the game with only Drippy + dependencies installed. Could be a mod conflict.

**Comment by Keksuccino** [comment]
Closed because no response and not reproducible.
