### ISSUE TITLE
Minecraft Crashes

### ISSUE THREAD

**Issue by UltraBeany** [Keksuccino/Drippy-Loading-Screen#38]
Every time I launch Minecraft with this mod, it instantly crashes. I have downloaded the dependencies and even launched it with only the mod and the dependencies and it still crashes. I am launching version 2.1.1 on forge with konrete version 1.6.0 and auudio version 1.0.3.

I expected that there was a incompatible mod when it crashed. When I launched minecraft with only the Dependencies and the mod itself, it still didn't work.

**Screenshots**
![Screenshot 2023-02-11 134138](https://user-images.githubusercontent.com/125151915/218275545-914b64f4-b237-4135-84e9-df51d3569763.png)

 - OS: Windows 11 Home (22h2)
 - Drippy Version: 2.1.1
 - Forge/Fabric Version: Forge 44.1.0
 - Minecraft Version: 1.19.3
 - Active Mods: drippyloadingscreen, konkrete, auudio

**Comment by Keksuccino** [comment]
Dude I need a log. I can't do anything with just a screenshot.

Please send me your `logs/latest.log` file after the game crashed. NOT the crash log. It has to be the latest.log.
Thank you very much.
