### ISSUE TITLE
Game Booting Delay Featire

### ISSUE THREAD

**Issue by WeaponGod243** [Keksuccino/Drippy-Loading-Screen#4]
So I'm using a GIF as the loading screen. But the game loads much fast than the GIF has a chance to even play out.
If there was a feature to delay the game starting to let the loading screen play out, I think that would be very beneficial.

Of course I could solve this by making the gif faster, but it's just not as cool right?

**Comment by Keksuccino** [comment]
Hmmm, I understand what you want to do and I do see cool things you could do with this, but I don't know if I want to add something to make the loading screen taking longer to finish :/ This could be very annoying for some people.. Sorry, but I will not add this :(
