### ISSUE TITLE
Forge Memory + Status: Add option to change text color

### ISSUE THREAD

**Issue by HazardEST** [Keksuccino/Drippy-Loading-Screen#41]
in the previous versions before 2.x you could change them in the layout

customization {
  textcolor = 00AAAA
  action = editforgememoryinfo
}

customization {
  textcolor = FFFFFF
  action = editforgestatustext
}

something like that
but now there is no way at all to do that

**Comment by Keksuccino** [comment]
Just replace it with a text element with placeholders.

**Comment by Keksuccino** [comment]
I fully dropped support for Forge's custom loading screen stuff with Drippy v3.0.0 and it won't come back, so I'm closing this, sorry.
