### ISSUE TITLE
Incompatibility with Dark Loading Screen

### ISSUE THREAD

**Issue by MCAlexisYT** [Keksuccino/Drippy-Loading-Screen#44]
How to reproduce:
1: Download Drippy Loading Screen, DarkLoadingScreen, and a whole bunch a fabric optimization mods (as a possible culprit)
2: Start up the game
3: Click on the [ MOJANG ] box
4: Make menus appear
5: WHAT AM I EVEN LOOKING AT
Demonstration video:

https://user-images.githubusercontent.com/78766083/220208805-2f147a3f-0afe-4b9d-b485-5a985bdfb781.mp4

**Comment by MCAlexisYT** [comment]
@Keksuccino This isn't quite right...

**Comment by Keksuccino** [comment]
Why do you have two loading screen mods installed at the same time? Is it working without DarkLodingScreen?? If so, just delete DarkLoadingScreen..

**Comment by MCAlexisYT** [comment]
Clarification:
1: The old title described how it looked like to me
2: I knew it probably wasn't a good idea to do it in the first place. I then made sure that I was right about that potential incompatibility (at first I thought that my game froze, and I was wrong about the freezing), documented it, deleted the offending mod, the end.

**Comment by MCAlexisYT** [comment]
@Keksuccino Also, you should add that to the mod incompatibility list (if you haven't done that already) and deliberately make it incompatible with the DarkLoadingScreen so that a Fabric Mod Incompatibility window thing opens and says something along the lines of "Drippy Loading Screen has seriously conflicted with DarkLoadingScren". (or you could just make it check for the offending mod and if true, it sends a warning message upon starting the game.)

**Comment by Keksuccino** [comment]
Added the mod to the incompatibility list! Thank you for telling me!
