### ISSUE TITLE
Splash Text not appearing and Text Elements Displaying Incorrectly

### ISSUE THREAD

**Issue by Mykosayyad** [Keksuccino/Drippy-Loading-Screen#46]
**Describe the bug**
The splash text isn't appearing, and the text elements aren't displaying the contents of it properly.

**To Reproduce**
1. Add a text element, click on text contents, add active mods as the content, and confirm.
2. Add a splash screen
3. Launch Minecraft
**Expected behavior**
A clear and detailed description of what you expected to happen.

**Game Log**
Please always include your `.minecraft/logs/latest.log` file **right after the issue happened**.
Please don't send the whole log as plain text here. Upload the file to https://gist.github.com and send the link.
DON'T SEND LOG SNIPPETS OR CRASH LOGS, PLEASE SEND THE WHOLE LATEST.LOG FILE!

**Screenshots**
In Editor: ![image](https://user-images.githubusercontent.com/102385088/226185348-bd7ccf7b-608a-43bf-bd56-be5d903ad1b2.png)

In Game: ![image](https://user-images.githubusercontent.com/102385088/226184295-efdf1725-1676-4e25-b545-13f8386091c4.png)

**Basic Informations (please complete the following information):**
 - Windows
 - drippyloadingscreen_forge_2.1.1_MC_1.18.2.jar
 - Forge 40.2.0
 - 1.18.2

 - Active Mods:
 
<details>
 [Awesome Dungeon Nether edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-nether-forge)
[Gaggle of Golems (by skilos609)](https://www.curseforge.com/minecraft/mc-mods/gaggle-of-golem)
[JEI Enchantment Info (by Phylogeny)](https://www.curseforge.com/minecraft/mc-mods/jei-enchantment-info)
[Reliquary Reincarnations (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/reliquary-v1-3)
[Atlas Lib (by smileycorp)](https://www.curseforge.com/minecraft/mc-mods/atlas-lib)
[Chunk Loaders (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/chunk-loaders)
[Simply Swords [Fabric & Forge] (by sweenuss)](https://www.curseforge.com/minecraft/mc-mods/simply-swords)
[Decorative Blocks (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
[Drippy Loading Screen [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/drippy-loading-screen)
[EnhancedVisuals (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/enhancedvisuals)
[Immersive Weathering [FORGE] (by OrdanaryMods)](https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-forge)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[SebastrnLib (by ItsSebastrn)](https://www.curseforge.com/minecraft/mc-mods/sebastrnlib)
[Integrated Dungeons and Structures (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/idas)
[FastWorkbench (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)
[Dynamic Trees - Biomes O' Plenty (by cadaverous_queen)](https://www.curseforge.com/minecraft/mc-mods/dtbop)
[Dynamic Trees (by ferreusveritas)](https://www.curseforge.com/minecraft/mc-mods/dynamictrees)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Silent's Gems (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silents-gems)
[Tinkers Construct (by mDiyo)](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[CoFH Core (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/cofh-core)
[Alcocraft: Beer & Stuff (by hadrus91)](https://www.curseforge.com/minecraft/mc-mods/alcocraft-beer-and-stuff)
[Awesome Dungeon - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-forge)
[Magnesium/Rubidium Extras (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
[Feature NBT Deadlock Be Gone (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/feature-nbt-deadlock-be-gone)
[Slimy Stuff (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/slimy-stuff)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Obscure API (by ObscuriaOfficial)](https://www.curseforge.com/minecraft/mc-mods/obscure-api)
[Silent Gear (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silent-gear)
[Applied Energistics 2 (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Rare Ice (Forge/Fabric) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/rare-ice)
[Mowzie's Mobs (by bobmowzie)](https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs)
[Applied Cooking (by ItsSebastrn)](https://www.curseforge.com/minecraft/mc-mods/applied-cooking)
[FancyMenu [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/fancymenu-forge)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[Macaw's Bridges - Oh The Biomes You'll Go (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-oh-the-biomes-youll-go)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[This Rocks! (Forge) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/this-rocks-forge)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Mekanism Generators (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators)
[Delightful (by brdbrn)](https://www.curseforge.com/minecraft/mc-mods/delightful)
[Mantle (by mDiyo)](https://www.curseforge.com/minecraft/mc-mods/mantle)
[Awesome Dungeon Ocean edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-edition-ocean-forge)
[Wireless Chargers (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/wireless-chargers)
[Dynamic View[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/dynamic-view)
[Integrated API (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/integrated-api)
[FastSuite (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastsuite)
[The Graveyard (FORGE) (by finallion_13)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge)
[Undead Expansion (by Fredzik2)](https://www.curseforge.com/minecraft/mc-mods/undead-expansion)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Small Ships [Fabric & Forge] (by talhanation)](https://www.curseforge.com/minecraft/mc-mods/small-ships)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Valhelsia Core (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)
[Meet Your Fight (by Lykrast)](https://www.curseforge.com/minecraft/mc-mods/meet-your-fight)
[Entity Collision FPS Fix (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix)
[Nether Portal Spread (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread)
[MCA Reborn [Fabric/Forge] (by jahx_senpoopie)](https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn)
[Ice and Fire: Dragons (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons)
[Stalwart Dungeons (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/stalwart-dungeons)
[Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
[Fins and Tails (by fusionstudiomc)](https://www.curseforge.com/minecraft/mc-mods/fins-and-tails)
[Controllable (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/controllable)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[NoCube's Sea Dwellers (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/nocubes-sea-dwellers)
[Ars Nouveau (by baileyholl2)](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau)
[Farmer's Respite (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/farmers-respite)
[Xaero's Minimap - Modded Support (by babybluetit)](https://www.curseforge.com/minecraft/texture-packs/xaeros-minimap-modded-support)
[Valhelsia Structures (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures)
[NoCube's Villagers Sell Animals (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/villagers-sell-animals)
[Polymorph (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Darker Depths (by naterbobber)](https://www.curseforge.com/minecraft/mc-mods/darker-depths)
[Clickable advancements[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/clickable-advancements)
[Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
[Mekanism Tools (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Compact Ores (by DoubleNegation)](https://www.curseforge.com/minecraft/mc-mods/compact-ores)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[River Treasures (by TrueRealCursed_Warrior)](https://www.curseforge.com/minecraft/mc-mods/river-treasures)
[Ars Creo (by baileyholl2)](https://www.curseforge.com/minecraft/mc-mods/ars-creo)
[Additional Structures (by XxRexRaptorxX)](https://www.curseforge.com/minecraft/mc-mods/additional-structures)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Savage & Ravage (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/savage-and-ravage)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[SimpleOres (by skrallexy)](https://www.curseforge.com/minecraft/mc-mods/simpleores)
[Abnormals Delight (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/abnormals-delight)
[YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Better Animals Plus (by cybercat5555)](https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus)
[Dynamic Trees - Quark (by supermassimo0310)](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-quark)
[Whisperwoods (by itsmeowdev)](https://www.curseforge.com/minecraft/mc-mods/whisperwoods)
[Guard Villagers (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Mob Compack (by BottomTextCf28)](https://www.curseforge.com/minecraft/mc-mods/mob-compack)
[Brandon's Core (by brandon3055)](https://www.curseforge.com/minecraft/mc-mods/brandons-core)
[ATO - All the Ores (by ATMTeam)](https://www.curseforge.com/minecraft/mc-mods/ato)
[Just Enough Effect Descriptions (JEED) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[[SBM] Bone Torch (by BuiltBroken)](https://www.curseforge.com/minecraft/mc-mods/sbm-bone-torch)
[Bygone Nether (by izofar)](https://www.curseforge.com/minecraft/mc-mods/bygone-nether)
[Majrusz's Progressive Difficulty (by Majrusz17)](https://www.curseforge.com/minecraft/mc-mods/majruszs-progressive-difficulty)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Exotic Birds (by ThePavoReality)](https://www.curseforge.com/minecraft/mc-mods/exotic-birds)
[YUNG's Extras (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras)
[AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
[Industrial Foregoing (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing)
[MrCrayfish's Gun Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod)
[Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials)
[Goblins & Dungeons (by superlord_9362)](https://www.curseforge.com/minecraft/mc-mods/goblins-dungeons)
[Apex Guns (by acherlins)](https://www.curseforge.com/minecraft/mc-mods/apex-guns)
[Alex's Delight (by NCP_Bails)](https://www.curseforge.com/minecraft/mc-mods/alexs-delight)
[Awesome Dungeon The End edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-the-end-forge)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[The Hordes (by smileycorp)](https://www.curseforge.com/minecraft/mc-mods/the-hordes)
[Konkrete [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Another Furniture (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/another-furniture)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[Gateways to Eternity (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/gateways-to-eternity)
[The Undergarden (by Quek04)](https://www.curseforge.com/minecraft/mc-mods/the-undergarden)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
[Aquamirae (by ObscuriaOfficial)](https://www.curseforge.com/minecraft/mc-mods/ob-aquamirae)
[Create Confectionery (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-confectionery)
[Just Enough Professions (JEP) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep)
[LibX (by noeppinoeppi)](https://www.curseforge.com/minecraft/mc-mods/libx)
[Additional Guns (by AutovwDev)](https://www.curseforge.com/minecraft/mc-mods/additional-guns)
[Silent Lib (silentlib) (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silent-lib)
[Create Enchantment Industry (by dragons_plus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
[Quark Oddities (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark-oddities)
[Advanced Chimneys (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/advanced-chimneys)
[Draconic Evolution (by brandon3055)](https://www.curseforge.com/minecraft/mc-mods/draconic-evolution)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Dungeons Plus (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/dungeons-plus)
[Colossal Chests (by kroeser)](https://www.curseforge.com/minecraft/mc-mods/colossal-chests)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Enchanting Infuser [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/enchanting-infuser-forge)
[Cooking for Blockheads (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads)
[TerraForged (by won_ton_)](https://www.curseforge.com/minecraft/mc-mods/terraforged)
[Create : Misc & Things (by to0pa_fr)](https://www.curseforge.com/minecraft/mc-mods/create-misc-and-things)
[Water Strainer (by Ruuubi)](https://www.curseforge.com/minecraft/mc-mods/water-strainer)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Useless Sword (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/useless-sword)
[JEI Integration (by SnowShock35)](https://www.curseforge.com/minecraft/mc-mods/jei-integration)
[Dungeons Libraries (by Patrigan)](https://www.curseforge.com/minecraft/mc-mods/dungeons-libraries)
[CodeChicken Lib 1.8.+ (by covers1624)](https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8)
[Large Ore Deposits (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Smarter Farmers (farmers replant) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/smarter-farmers-farmers-replant)
[Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
[Dynamic Trees - TerraForged (by HarleyOConnor)](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-terraforged)
[Amplified Nether (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/amplified-nether)
[Dungeons Gear (by the_infamous_1)](https://www.curseforge.com/minecraft/mc-mods/dungeons-gear)
[Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
[Every Compat (Wood Good) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/every-compat)
[Corail Woodcutter (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter)
[Immersive Engineering (by BluSunrize)](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering)
[Compat O' Plenty (by tdstress)](https://www.curseforge.com/minecraft/mc-mods/compat-o-plenty)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Terralith (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/terralith)
[Born in Chaos (by mongoose_artist)](https://www.curseforge.com/minecraft/mc-mods/born-in-chaos)
[Nature's Aura (by Ellpeck)](https://www.curseforge.com/minecraft/mc-mods/natures-aura)
[Immersive Armors [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-armors)
[Basic Nether Ores [Forge/Fabric] (by cScotPlay)](https://www.curseforge.com/minecraft/mc-mods/basic-nether-ores)
[Gilded Ingot (by Intijir)](https://www.curseforge.com/minecraft/mc-mods/gilded-ingot)
[Just Enough Advancements (JEA) (by MelanX)](https://www.curseforge.com/minecraft/mc-mods/jea)
[Iron Furnaces [FORGE] (by XenoMustache)](https://www.curseforge.com/minecraft/mc-mods/iron-furnaces)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[ToroHealth Damage Indicators (by ToroCraft)](https://www.curseforge.com/minecraft/mc-mods/torohealth-damage-indicators)
[Forgiving World - Dimension Stacking[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/forgiving-world)
[Pollution of the Realms (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realms)
[Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[JER Integration (by AlasDiablo)](https://www.curseforge.com/minecraft/mc-mods/jer-integration)
[Biome Makeover (Forge) (by Lemonszz)](https://www.curseforge.com/minecraft/mc-mods/biome-makeover-forge)
[Thermal Foundation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-foundation)
[Structures' Compass (by Samarium_150)](https://www.curseforge.com/minecraft/mc-mods/structures-compass)
[SimpleCore API (by skrallexy)](https://www.curseforge.com/minecraft/mc-mods/simplecore-api)
[Configured (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Repurposed Structures (Forge) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures)
[Thermal Expansion (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-expansion)
[YUNG's Bridges (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-bridges)
[Create Stuff & Additions (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions)
[Visual Workbench (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Lucky TNT Mod (Too Much TNT) (by Fleshcrafter_)](https://www.curseforge.com/minecraft/mc-mods/luckytnt)
[Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Trash Cans (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/trash-cans)
[Traveler's Titles (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/travelers-titles)
[BrassAmber BattleTowers (by sMilamber)](https://www.curseforge.com/minecraft/mc-mods/brassamberbattletowers)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Mystical Oak Tree (by plantspookable)](https://www.curseforge.com/minecraft/mc-mods/mystical-oak-tree)
[FastFurnace (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastfurnace)
[Oh The Biomes You'll Go (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
[Iron Chests (by ProgWML6)](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[Sons Of Sins (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/sons-of-sins)
[Aquaculture 2 (by Shadowclaimer)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[Magnum Torch (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/magnum-torch-forge)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[Titanium (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/titanium)
[Just Enough Immersive Multiblocks (by aronson_1)](https://www.curseforge.com/minecraft/mc-mods/just-enough-immersive-multiblocks)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Mekanism (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism)
[Geode+ [Forge/Fabric] (by YeoXuHang)](https://www.curseforge.com/minecraft/mc-mods/geode-plus)
[Create Cafe (by 1mphuls3)](https://www.curseforge.com/minecraft/mc-mods/create-cafe)
[Just Enough Calculation (by towdium)](https://www.curseforge.com/minecraft/mc-mods/just-enough-calculation)
[ForgeEndertech (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/forgeendertech)
[Just Enough Painting Previews (JEPP) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/jepp)
[Majrusz Library (by Majrusz17)](https://www.curseforge.com/minecraft/mc-mods/majrusz-library)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Flywheel (by jozufozu)](https://www.curseforge.com/minecraft/mc-mods/flywheel)
[Cyclops Core (by kroeser)](https://www.curseforge.com/minecraft/mc-mods/cyclops-core)
[The Wild Backport (by blackgear27)](https://www.curseforge.com/minecraft/mc-mods/the-wild-backport)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
</details>

**Comment by Keksuccino** [comment]
Dude what are these "placeholders"? These are not valid placeholders. They can't work.

When editing the content of the text elements, click on the little Plus button at the right side of the text box to add placeholders to your text element.

**Comment by Keksuccino** [comment]
Closed because no response and probably just user error.
