### ISSUE TITLE
[FancyMenu] Incompatibility with Screenshot Viewer

### ISSUE THREAD

**Issue by qingchunnh** [Keksuccino/Drippy-Loading-Screen#49]
My game crashed due to lack of RAM, after which I started the game again the Drippy Loading Screen function did not work, the game crashed with a java.lang.reflect.InvocationTargetException: null, I deleted the menu_identifiers.db and user_variables.db files and they are back to normal, is this due to my corrupt files?

**Comment by qingchunnh** [comment]
I don't speak English, the above is the result of the translator

**Comment by qingchunnh** [comment]
I found that the game still crashes, after deleting customizablemenus.txt it is back to normal, the game will not crash until the crash caused by insufficient ARM

**Comment by qingchunnh** [comment]
I'm sorry, I found the details, it's a fancymenu issue not a Drippy Loading Screen issue, the mod that causes the game to crash is https://www.curseforge.com/minecraft/mc-mods/screenshot-viewer. When Universak Layoutsz crashes on restarting the game after the GUI is enabled in the screenshot viewer, game version 1.18.2. i'm sorry!

**Comment by Keksuccino** [comment]
Moved this to an issue in FancyMenu's GitHub repo! :)
