### ISSUE TITLE
[incompatibility] Breaks Dash Loader

### ISSUE THREAD

**Issue by MissGamerz** [Keksuccino/Drippy-Loading-Screen#5]
**Describe the bug**
this mod doesnt allow Dash loader to run its cache event after loading screen

I do not think this is a issue with dash loader more you guys are overriding events dash loader listens for to start caching

**To Reproduce**
install Drippy loading Screen (1.1.1) customise the loading screen, install dash loader (2.0)
 
**Expected behaviour**
dash loader to cache the textures like its supposed to without interruption

**Comment by OverloadedWithMods** [comment]
I have this and just came to the issues to see if it was already reported

**Comment by Keksuccino** [comment]
Closed because full rewrite of mod. If this is still a problem, please open a new issue.
