### ISSUE TITLE
Crash on client with exit code -1: The game crashed whilist rendering overlay

### ISSUE THREAD

**Issue by vinnyg0621** [Keksuccino/Drippy-Loading-Screen#54]
**Describe the bug**
Description: Rendering overlay,
java.lang.NullPointerException: Cannot invoke "de.keksuccino.konkrete.config.Config.getOrDefault(String, Object)" because "de.keksuccino.drippyloadingscreen.DrippyLoadingScreen.config" is null

**Expected behavior**
I expected my custom loading screen to come up

**Game Log**
[/c037e561c343f0e2ab000fd86eb2b484)](https://gist.github.com/vinnyg0621/c037e561c343f0e2ab000fd86eb2b484)

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - Drippy Version: 2.2.0
 - Forge/Fabric Version: Forge 43.2.8
 - Minecraft Version 1.19.2
 - Active Mods: Optifine, JEI

**Comment by Keksuccino** [comment]
Update to the latest Drippy build.

**Comment by vinnyg0621** [comment]
I just did that
