### ISSUE TITLE
Stackoverflow when getting the mojang logo's attributes

### ISSUE THREAD

**Issue by tt-thoma** [Keksuccino/Drippy-Loading-Screen#55]
**Describe the bug**
I'm trying to put a progress bar with a size that matches the Mojang Logo, that itself uses vanilla calculations. The only problem is, when I try to do that using the advanced sizing, the game straightforward crashes.

**To Reproduce**
1. Edit the Minecraft Loading screen
2. Right click the mojang logo and select `Pick Element > Mojang Logo`
3. Add a new progress bar
4. Move it, right click on it and edit the `Advanced Sizing > Width` option
5. Put a `GUI > Element Width` place holder
6. Paste the ID in the `id` field

**Expected behavior**
The progress bar has the same size as the Mojang Logo

**Game Log**
https://gist.github.com/tt-thoma/28c86c57764add6729ab181f872ad23c

**Screenshots**
No

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - Drippy Version: drippyloadingscreen_forge_2.2.1_MC_1.18.2.jar
 - Forge/Fabric Version [e.g. 31.2.24]
 - Minecraft Version [e.g. 1.15.1]
 - Active Mods: https://legacy.curseforge.com/minecraft/modpacks/kast/relations/dependencies - Latest version of each mod, but Create 0.5.i and DrippyLoadingScreen

**Comment by tt-thoma** [comment]
None of the mods seems related to the loading screen

**Comment by Keksuccino** [comment]
FancyMenu v3.0.0 and Drippy v3.0.0 are out now and they are full rewrites, so I'm closing this for now. If it still happens, please open a new issue, thank you.
