### ISSUE TITLE
crash client Forge 1.19.2 latest version mod and forge

### ISSUE THREAD

**Issue by GitJhopa** [Keksuccino/Drippy-Loading-Screen#58]
[crash-2023-07-01_03.52.56-client.txt](https://github.com/Keksuccino/Drippy-Loading-Screen/files/11923856/crash-2023-07-01_03.52.56-client.txt)

**Comment by Keksuccino** [comment]
Please update Drippy, FancyMenu and Konkrete to the latest versions.

**Comment by GitJhopa** [comment]
updated... crash.

**Comment by Keksuccino** [comment]
It says it can't find something in FancyMenu I added weeks or months ago. What version of FancyMenu do you use?

**Comment by GitJhopa** [comment]
fixed.
