### ISSUE TITLE
[1.19.2] TTF font is not displayed and it hides images as well

### ISSUE THREAD

**Issue by vgrynch** [Keksuccino/Drippy-Loading-Screen#59]
I added TTF font via the resource pack. After that, the loading screen stopped displaying not only all texts but also all custom images. After the games load, when it loading screen fades out to the main game screen, everything appears correctly as it should for the moment (for the duration of fading out). Also, when opening the loading screen for design preview or editing, everything works well.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Install any TTF font resource pack. Let me know if need help with this, though it is easy to do.
2. Start Minecraft with a custom loading screen that contains both texts and images.
3. Observe texts and images disappear, only the loading progress bar and Mojang logo are displayed.
4. Observe everything appears correctly during the fade-out only, or when opening the loading screen for editing.

**Expected behavior**
Texts and images are displayed correctly right from the start when the loading screen appears if installing TTF font via the resource pack.

**Comment by vgrynch** [comment]
Also, when removing all texts on the screen and leaving just images, they are all displayed just fine. So this is something related to only texts. I can workaround it all by replacing texts with their respective images, but scaling would suffer much :(

**Comment by Keksuccino** [comment]
Hi! It’s still a loading screen. The font doesn't work, because it gets loaded in the loading screen. I don't think I can (or should?) fix this, sorry.
