### ISSUE TITLE
[1.17.1] Will not load with Forge .71

### ISSUE THREAD

**Issue by ProsperCraft** [Keksuccino/Drippy-Loading-Screen#6]
**Describe the bug**
[main/ERROR] [mixin/]: Mixin config drippyloadingscreen.mixin.json does not specify "minVersion" property'

Forge includes mixins now.

**Comment by Keksuccino** [comment]
Hi!

Forge ships with Mixin since MC 1.15, so that's nothing new in Forge 37.0.71 ^^

The "error" you see is more a warning than an actual error and will not cause your client to crash.

Please send me your full `.minecraft/logs/latest.log` file.

**Comment by ProsperCraft** [comment]
I get a proper crash report now-
https://gist.github.com/ProsperCraft/a5f4eee451c53884297d1e894cf41fa1

Debug-
https://gist.github.com/ProsperCraft/21aa91b8cf0d2f20d225a4c8667f3ae0

Latest-
https://gist.github.com/ProsperCraft/689f462eba276e49e47bf2dcd9422dd5

**Comment by ProsperCraft** [comment]
PS your fabric version needs to be flagged as Fabric so it doesn't show up in the curseforge launcher when selecting mods.

**Comment by Keksuccino** [comment]
This isn't possible anymore. You can't set the Fabric tag anymore. Blame CurseForge, not me :D

**Comment by Keksuccino** [comment]
> I get a proper crash report now-
> https://gist.github.com/ProsperCraft/a5f4eee451c53884297d1e894cf41fa1
> 
> Debug-
> https://gist.github.com/ProsperCraft/21aa91b8cf0d2f20d225a4c8667f3ae0
> 
> Latest-
> https://gist.github.com/ProsperCraft/689f462eba276e49e47bf2dcd9422dd5

You have one or more mods installed that change the loading screen, just like Drippy, which should be the first thing to check when facing client crashes with multiple mods installed ^^ In your case, it's most probably "Memory Usage Screen", which isn't compatible with Drippy. Could be more than just one mod, but that's the first mod you need to remove.

Hope this fixes the crash. If you still have problems after checking your mods for conflicts, please open a new issue here :)
