### ISSUE TITLE
Red overlay on Loading Screen

### ISSUE THREAD

**Issue by SHXRKIIE** [Keksuccino/Drippy-Loading-Screen#60]
**Describe the bug**
So when creating a Loading Screen for my Fear Nightfall Modpack, is makes a Red overlay on the Loading Screen.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Install Fear Nightfall Modapck
2. Add Drippy
3. Make Loading Screen
4. Relaunch
5. Red overlay on Background

**Expected behavior**
When setting the background for my modpack with Drippy Loading Screen the background is red still? The screenshot I used is from in game.

**Game Log**
https://gist.github.com/SHXRKIIE/2961a788a78dc24f7d979fc5ca80f396

**Screenshots**
![NVIDIA_Share_jplw89KIxa](https://github.com/Keksuccino/Drippy-Loading-Screen/assets/79353591/f34378cc-198c-4128-af6c-52d0abc1886d)

**Basic Informations (please complete the following information):**
 - OS: W11
 - Drippy Version drippyloadingscreen_forge_2.2.2_MC_1.19.1-1.19.2.jar
 - Forge/Fabric Version 43.3.2
 - Minecraft Version 1.19.2
 - Active Mods Fear Nightfall Modpack Mods List - https://gist.github.com/SHXRKIIE/cc92dc3a9233265cb6d290eb78b64361

**Comment by Keksuccino** [comment]
EnhancedVisuals is causing this: https://fm.keksuccino.dev/en/incompatibility-list
