### ISSUE TITLE
{bug} Using mojang splash text crashes game

### ISSUE THREAD

**Issue by Xplodin** [Keksuccino/Drippy-Loading-Screen#61]
https://gist.github.com/Xplodin/c13b4b52c40566d66ffe81cae3e37871

crashlog^

was editing my loading screen for the game startup and as soon as I added the mojanglike splash text it crashed. 

Sorry for the blank issue, issue template leads me to a blank nonexistent website on operagx

https://github.com/Keksuccino/Drippy-Loading-Screen/assets/13007677/5b04fc65-e6e0-4922-9124-41fc11a96875

**Comment by Keksuccino** [comment]
FancyMenu v3.0.0 + Drippy v3.0.0 are out now and they are full rewrites, so I'm closing this for now. If it still happens, please open a new issue, thank you.
