### ISSUE TITLE
A gif file is corrupted when uploaded 

### ISSUE THREAD

**Issue by a3sthos** [Keksuccino/Drippy-Loading-Screen#69]
I made a logo gif with canva , animated.Put it in assets , then to the loading screen but it is corrupted and all i see is dots.

Tried to repair the file from various sites but the gif file is fine.The problem is i cant see nothing but dots animating at menu.

Minecraft version 1.20.1

**Comment by Keksuccino** [comment]
This is not a bug, but a limitation of the GIF API. Try to use no interlacing, transparency and other special stuff when making the GIF.
