### ISSUE TITLE
[1.17.1-Forge] Crash when creating a new layout to customize.

### ISSUE THREAD

**Issue by Gbergz** [Keksuccino/Drippy-Loading-Screen#7]
**Describe the bug**
When clicking the "New" (create new layout) button, the game crashes to desktop.

**To Reproduce**
1. Enter the Customization screen.
2. Click Loading Screen
3. Click Layouts.
4. Click New.
5. Crash.

**Expected behavior**
That no crash happens when trying to customize the loading screen.

**Crash Log**
https://gist.github.com/Gbergz/2d65f41c46cb477791c615d56810a736

**Screenshots** (GIF)
https://user-images.githubusercontent.com/26634554/134932253-7289323b-68e4-4519-9fc2-dc7db96348f4.mp4

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - Drippy Loading Screen Version : 1.2.0 (https://www.curseforge.com/minecraft/mc-mods/drippy-loading-screen/files/3470678)
 - Forge Version: 37.0.70
 - Minecraft Version 1.17.1
 - Active Mods : https://gist.github.com/Gbergz/db786156fe25a012954109ba49555584

**Comment by Keksuccino** [comment]
This is most probably a mod conflict. Please try to start the game with only Drippy + dependencies enabled.

**Comment by Gbergz** [comment]
Late reply, just tried this with Drippy + dependencies. Still crashes.
https://gist.github.com/Gbergz/62eac00246e5625ef653f98dd522cc94

**Comment by Keksuccino** [comment]
Well, you was totally right and I have absolutely no clue why nobody except of you reported this to me :D
It's fixed in v1.2.0-1 for MC Forge 1.17, thank you for your report! :)
