### ISSUE TITLE
I don't see anything

### ISSUE THREAD

**Issue by jrcp2612** [Keksuccino/Drippy-Loading-Screen#74]
I have a problem when I zoom in version 1.19.2 (and in the latest version of the mod) and when I hit zoom then I can't see anything, who can help me please
![2024-07-12_17 04 58](https://github.com/user-attachments/assets/d446074b-b813-4694-a45a-cbe7509fa8b6)

**Comment by Keksuccino** [comment]
That can't be related to Drippy Loading Screen. If it only happens with Drippy installed, check for mod conflicts.
For more support, please join the Discord: https://discord.gg/rhayah27GC
