### ISSUE TITLE
Modrinth Mod Incompatibility link missing

### ISSUE THREAD

**Issue by DemonsHearts** [Keksuccino/Drippy-Loading-Screen#78]
okay so it isn't exactly a mod incompatibility but something about it
the link isn't present on the modrinth app/website making it hard for modrinth user to check the list
![image](https://github.com/user-attachments/assets/3d888c4a-a409-4577-b7e3-3dfbab9f6a0e)
though it is present on the curseforge page, but since im mainly using modrinth now it is kind of bugging me
![image](https://github.com/user-attachments/assets/2a542202-571a-49cc-a9b8-addbc3b5e1df)

**Comment by Keksuccino** [comment]
Fixed.
