### ISSUE TITLE
Port 'element' orientation of FancyMenu to Drippy

### ISSUE THREAD

**Issue by MrPeterman** [Keksuccino/Drippy-Loading-Screen#8]
Instead of aligning elements to an orientation in the window, is it possible to add a way to sort of 'attach' a gui element to another element? It's basically to maintain the relative postions different elements to eachother while scaling the window.
Example of how i configured loading screen in a maximized window:
![image](https://user-images.githubusercontent.com/34008890/138008805-bf2e8963-4cf3-4ec7-95cc-df869efb3264.png)
How it looks in a smaller window:
![image](https://user-images.githubusercontent.com/34008890/138008942-ccb02fe5-483e-4f2b-a768-bf152f5b0b2d.png)
(So here the progressbar under the Mojang logo and the command slideshow next to the Forge Loading Status are moved drastically)

**Comment by Keksuccino** [comment]
Hi! Will probably port the `element` orientation from FancyMenu soon, but you can already sort of do this by just using the same orientation for elements you don't want to overlap :)

**Comment by XxMr1234GamerzxX** [comment]
could you not just do this for all the options? like color support for text (using color codes) just import like the whole editor instead of recreating it from the ground up, you've for the most part already done this

> Hi! Will probably port the `element` orientation from FancyMenu soon, but you can already sort of do this by just using the same orientation for elements you don't want to overlap :)

**Comment by Keksuccino** [comment]
Well, things are not always the same just because they look the same.
For example, Drippy uses its own render engine for text, because the normal one isn't even loaded when the loading screen is shown for the first time.
Btw, there is color support for text, if I'm not wrong. You can set a color using HEX.

**Comment by Keksuccino** [comment]
The mod is now a FancyMenu extension, which means it has all features FancyMenu has, including orientations.
