### ISSUE TITLE
Not showing early enough on neoforge

### ISSUE THREAD

**Issue by vaporvee** [Keksuccino/Drippy-Loading-Screen#80]
The custom loading screen just appears at the end of loading neoforge for a few seconds. Maybe add support for basic customization for [neoforged/FancyModLoader](https://github.com/neoforged/FancyModLoader). The animated fox is on the root of it. The background adjusts to `darkMojangStudiosBackground` in `options.txt`. Maybe custom colors and changable loading icon? I don't know how customizable it is because it's a pretty critical part of neoforge.

**Comment by Keksuccino** [comment]
I will not add support for the early loading screen of Forge and NeoForge, sorry.
