### ISSUE TITLE
[1.20.1] crash on start up with version 3.0.8

### ISSUE THREAD

**Issue by xg787** [Keksuccino/Drippy-Loading-Screen#81]
**Describe the bug**
load crash

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. load drippy 3.0.8
2. crash

**Expected behavior**
load

**Game Log**
[latest.log](https://github.com/user-attachments/files/17292195/latest.log)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - Drippy Version 3.0.8
 - Forge Version 47.3.11
 - Minecraft Version 1.20.1

**Comment by katubug** [comment]
Same issue

**Comment by QianFuv** [comment]
Same issue.

**Comment by Groupix05** [comment]
Same on Forge 47.3.10 on Linux

**Comment by Keksuccino** [comment]
Fixed in Drippy v3.0.9!
